### ISSUE TITLE
Macro todo!() is unstable

### ISSUE THREAD

**Issue by CowsertheKhelinace** [JonathanHelianthicusDoe/toonmux#1]
Even after updating to a nightly release of rustup, I still wasn't able to compile simply due to the todo macro.

` Compiling toonmux v0.0.2 (/home/cowser/toonmux/toonmux)`
`error[E0658]: macro todo! is unstable`
`  --> src/main.rs:89:51`
`   |`
`89 |                             Action::Talk(_key) => todo!(),`
`   |                                                   ^^^^^^^`
`   |`
`   = note: for more information, see https://github.com/rust-lang/rust/issues/59277`

`error[E0658]: macro todo! is unstable`
`   --> src/main.rs:131:47`
`    |`
`131 |                         Action::Talk(_key) => todo!(),`
`    |                                               ^^^^^^^`
`    |`
`    = note: for more information, see https://github.com/rust-lang/rust/issues/59277`

`error: aborting due to 2 previous errors`

`For more information about this error, try `rustc --explain E0658`.`
`error: Could not compile ``toonmux`.`

`To learn more, run the command again with --verbose.`

**Comment by JonathanHelianthicusDoe** [comment]
`todo!` is in the standard library on stable Rust version `>=1.40.0`:

<https://blog.rust-lang.org/2019/12/19/Rust-1.40.0.html#additions-to-the-standard-library>
